version: "3.5"

services:
  api01:
    image: diegoalexandrooliveira/rinha-back-end-q1-2024:1.0.0
    hostname: api01
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/rinha
      - DB_PASSWORD=123
      - DB_USERNAME=admin
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
  api02:
    image: diegoalexandrooliveira/rinha-back-end-q1-2024:1.0.0
    hostname: api02
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/rinha
      - DB_PASSWORD=123
      - DB_USERNAME=admin
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d rinha -U admin" ]
      interval: 2s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "340MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1