version: "3.5"

services:
  api01: &api
    # image: iscodand/rinha-2024q1-csharp-session
    build:
      dockerfile: RinhaCrebito/Dockerfile
    hostname: api01
    ports:
      - "8080:3001"
    depends_on:
      - rinha-db
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.45"
    #       memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8081:3002"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.15"
    #       memory: "10MB"
          
  rinha-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: rinha-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=R1nh4Cr3B1T0!
    ports:
      - "1433:1433"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.45"
    #       memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1